[IV-22-23] Objetivo 0: Supercatch
danielsp13/SuperCatch pull request #1
Opened 2022-09-30 18:03 UTC by danielsp13

Este es mi primer intento para superar el objetivo. Considero que el problema que planteo, y la solución que propongo son válidos, pero me gustaría revisar/confirmar si la lógica de negocio de la misma es demasiado ambiciosa o no.

2022-10-03 11:08 UTC, JJ commented
Por favor, realiza la lista de comprobación. Sin ella es muy probable que os falte alguna cosa para alcanzar el objetivo.

2022-10-03 11:11 UTC, JJ requested changes
Por favor, vuelve a repasar la lista de comprobación, ponla en el cuerpo del PR, y mira un item nuevo que se ha añadido hoy, que es relevante.

2022-10-03 11:11 UTC, JJ commented on README.md
> +Sin embargo, todos somos conscientes de que la elección del sitio donde compramos es importante, ya que no es lo mismo realizar la compra en una cadena conocida de supermercados a nivel nacional, que
Creo que sería ya el tercer "problema" de este estilo que no pasa el objetivo. "Elegir" es buscar. Por favor, consulta las lógicas de negocio aceptables (lo que podrías haber hecho si hubieras pasado la lista de comprobación)

2022-10-03 11:11 UTC, JJ commented on README.md
> +    En efecto. Desde siempre en mi familia hemos tenido la costumbre de realizar una compra responsable, maximizando siempre que se pueda el ahorro, pero también cuidando y teniendo el cuenta el desp
OK, veo que lo has hecho, pero tendrías que haberlo puesto en el cuerpo del PR.

2022-10-03 11:11 UTC, JJ commented on README.md
> +   Por supuesto. Se requiere obtener la lista de supermercados a una determinada distancia, así como los diferentes productos de cada uno.
¿Una aplicación en tu ordenador no puede conectarse a Internet y descargarse la lista?

2022-10-03 11:11 UTC, JJ commented on README.md
> +    (Pendiente de concretar, la respuesta es afirmativa, pero considero que puede llegar a ser una lógica complicada).
Esta es la más importante.

2022-10-03 16:10 UTC, danielsp13 commented on README.md
> +    (Pendiente de concretar, la respuesta es afirmativa, pero considero que puede llegar a ser una lógica complicada).
Buenas tardes profesor, acabo de ver toda la revisión. Antes de su revisión efectivamente me di cuenta de que no estaba siguiendo lo que se especificaba / se requiere. Es por ello, que he diseñado una nueva propuesta totalmente diferente del primer intento, siguiendo todos los pasos de diseño y posteriormente buscando una lógica de negocio acorde con la asignatura. Déjeme que revise todos los fallos y el nuevo item que ha introducido y realizaré una nueva petición.

2022-10-03 16:43 UTC, danielsp13 commented
* [x] ***¿Se trata de un problema real del que se tenga conocimiento personal?***

  No es un problema que me involucre a mi personalmente ni directamente. Sin embargo, además de obtener testimonios a través de uno de mis mejores amigos de toda la vida (que es jugador de fútbol en un equipo regional), también he podido comprobar de primera mano cuando le he acompañado en alguna que otra ocasión, cómo se realizaban dichos entrenamientos. Ahí fue cuando pensé en esta solución para optimizar las rutinas que hacían diariamente, con el objetivo de ayudar al cuerpo técnico a un posible mejor rendimiento. 

  También considero que esta solución podría ser extrapolable al ámbito personal, pues todos siempre hemos tenido la necesidad de organizarnos adecuadamente una rutina de ejercicio que garantice que sea equilibrada, efectiva, y atendiendo a nuestros propios atributos.

* [x] ***¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?***

  Por supuesto. Se requiere de un volumen de datos considerable (fichas, atributos de jugadores, listado de entrenamientos,..) además de determinados cálculos que hacen que la nube sea el lugar idóneo para esta solución. También hay que tener en cuenta que el equipo no tiene por qué entrenar siempre en el mismo lugar, por ejemplo si juega de visitante es posible que acuda a otras instalaciones, por tanto es esencial que se garantice el acceso desde cualquier parte.

* [x] ***¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?***

  Sí. *En primer lugar, como prerrequisito se requiere el acceso a las fichas de los jugadores y sus atributos, datos que debe proporcional la sección deportiva del club (léase sección de "modelo"), así como que el cuerpo técnico proporcione una lista con todos los ejercicios de entrenamiento que considere. ¿Esto último de los ejercicios también es necesario? Sí, es necesario a pesar de que se pueda pensar que son muchas inserciones, pero la aplicación debe ser flexible atendiendo a las ideas de dicho cuepo técnico (ejemplo: estaríamos muy limitados si los ejercicios son por defecto impuesto por nosotros / acceso a API, y de repente se produce un cambio de entrenador y ve que no le convencen los ejercicios de nuestra aplicación).*

  Con los datos anteriores se realizarán diversos cálculos como medias, desviaciones, varianzas, comparaciones estadísticas en general, con el objetivo de decidir los ejercicios finales de la sesión. También hay que tener en cuenta que hay que establecer algoritmos de decisión sobre la planificación: valorar que jugadores lesionados no pueden participar en las rutinas, o que un mismo jugador no debería participar en subgrupos con una dificultad/carga de ejercicio excesiva, y por supuesto, *debería haber un equilibrio en el orden de cómo estos se realizan*.

  Esta es la lógica de negocio que hay detrás. De lo único que se tiene que encargar el entrenador es de recibir la decisión de la aplicación, y posteriormente otorgar calificación a los jugadores para comprobar su evolución.

* [x] ***¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?***

  Sí, para ello acuda al apartado de este readme: *Secciones de Interés*.

* [ ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
Como menciono en el item 3 (lógica de negocio), se requiere una inserción previa de de datos para poder proceder.

2022-10-03 16:58 UTC, JJ requested changes
Has realizado un esfuerzo considerable, y creo que estás muy cerca de alcanzar el objetivo. Los principales problemas son
1. Concreta *el* problema que quieres resolver.
2. Asegúrate de que tienes datos sobre el mismo, sea de tu amigo o sea de datos liberados sobre fútbol.
3. Aclara la lógica de negocio que vas a usar. No hace falta que la inventes, simplemente sigue algún algoritmo conocido. Asegúrate también que resuelve el problema
4. Asegúrate de que vas a poder programar, sin usar ninguna biblioteca externa, esa lógica de negocio.

2022-10-03 16:58 UTC, JJ commented on README.md
> +En el deporte, la disciplina y el entrenamiento son dos máximas que se deben cumplir si se quieren conseguir unos determinados objetivos. Por supuesto, todos queremos evolucionar a una versión mejor
Ya ha habido varias propuestas relacionadas con el entrenamiento. También he hablado con entrenadores profesionales sobre el tema. Ninguno de ellos se plantea las rutinas de entrenamiento como un problema, y menos un problema donde haya que plantear algún procesamiento de información más allá de lo trivial (hay que tener cierta progresión, adaptar a la clase, y luego cada entrenador tiene sus rutinas)
Por eso os digo que tengáis conocimiento personal sobre un tema. Si ese es el caso y el resto de las preguntas de la lista (incluyendo que haya datos sobre el tema) se contestan afirmativamente, estoy dispuesto a comprártelo. Si no, desgraciadamente, y como en los otros casos, no parece que sea un problema del que se pueda sacar algo.

2022-10-03 16:58 UTC, JJ commented on README.md
> +Se plantea una solución al problema de la optimización y planificación de entrenamientos en forma de aplicación desplegada en la nube tal que:
Optimización ¿con respecto a qué? 
También he comentado que cualquier intento de solución de un problema *físico* es en la práctica imposible de validar. Pero una vez más, sigo leyendo.

2022-10-03 16:58 UTC, JJ commented on README.md
> +* Con los datos de los atributos de los jugadores y una lista de ejercicios de entrenamiento, analizar las características de la plantilla y decidir una planificación de una sesión diaría de entrenam
Comentas cosas como "atributos". ¿Tienes datos sobre esos atributos que puedas usar para testear? Si no, leer en el guión lo que dice sobre tener que introducir datos (o, para el caso, meter datos totalmente ficticios)
Comentas también "analizar las características". ¿Hay algún algoritmo *que tú conozcas* que se use para ello? ¿Podrías dar alguna pista del mismo? ¿Cómo validarías ese algoritmo, en caso de que existiera?

2022-10-03 16:58 UTC, JJ commented on README.md
> +* Permitir calificar a los jugadores observando una tendencia evolutiva en ellos, generando informes para cada uno en caso de que el entrenador lo requiera.
¿Qué tiene que ver esto con el problema?

2022-10-03 16:58 UTC, JJ commented on README.md
> +* Sugerir un 11 titular en función de los resultados y de la mejora de los atributos.
Mira, he trabajado con datos de fútbol y esto es una de las cosas que se puede hacer. No es fácil. Requiere aplicar algoritmos de redes complejas, aparte de analizar otra serie de parámetros; también tomar decisiones sobre cómo se va a organizar esa plantilla.
Una vez más, no sé si estás trabajando en tus ratos libres en una casa de apuestas qeu analiza resultados de fútbol o eres media punta profesional de equipo de la 1º RFEF (que he tenido a un alumno que lo era). Si no lo eres (pregunta 0: ¿tienes conocimiento personal del problema y de los datos necesarios para resolverlo?) es mejor que busques un problema que *sí* tengas conocimiento personal y tengas los datos para resolver.

2022-10-03 16:58 UTC, JJ commented on README.md
> +    No es un problema que me involucre a mi personalmente ni directamente. Sin embargo, además de obtener testimonios a través de uno de mis mejores amigos de toda la vida (que es jugador de fútbol e
OK, entonces la pregunta a lo de arriba es negativa. De 1º a las divisiones RFEF los jugadores y el equipo técnico tienen datos de los jugadores proporcionados por OPTA (algunos de esos datos son gratuitos, bien de esta empresa o de otra). Con todo el respeto a tu amigo, al que deseo lo mejor, no creo que un equipo regional tenga la infraestructura para almacenar ni procesar esos datos.

2022-10-03 16:58 UTC, JJ commented on README.md
> +    También considero que esta solución podría ser extrapolable al ámbito personal, pues todos siempre hemos tenido la necesidad de organizarnos adecuadamente una rutina de ejercicio que garantice qu
"También" en una respuesta de este tipo es mala respuesta. O tienes un cliente o tienes otro, o resuelves un problema u otro. Y ya te he dicho arriba que por ahí no hay ninguna tela que cortar.

2022-10-03 16:58 UTC, JJ commented on README.md
> +   Por supuesto. Se requiere de un volumen de datos considerable (fichas, atributos de jugadores, listado de entrenamientos,..) además de determinados cálculos que hacen que la nube sea el lugar idón
Por favor, mira lo que implica *diseñar* una aplicación en la nube. Un móvil con quadcore o, mejor, un portátil con un i7 tiene más capacidad de cálculo y es más fácil de trabajar con él en el banquillo.

2022-10-03 16:58 UTC, JJ commented on README.md
> +    Sí. *En primer lugar, como prerrequisito se requiere el acceso a las fichas de los jugadores y sus atributos, datos que debe proporcional la sección deportiva del club (léase sección de "modelo")
O haces lo de los ejercicios (que ya te digo que no tiene ninguna lógica de negocio más que buscar) o haces lo de diseño del equipo (que no es nada fácil, sobre todo si lo vas a programar tú)

2022-10-03 16:58 UTC, JJ commented on README.md
> +    Con los datos anteriores se realizarán diversos cálculos como medias, desviaciones, varianzas, comparaciones estadísticas en general, con el objetivo de decidir los ejercicios finales de la sesió
"Diversos cálculos" no resuelve el problema, y hacer cálculos por hacerlos tampoco es lo que se busca en la asignatura. Aplicar algoritmos simples sobre esas cantidades podría ser, pero sólo si planteas el problema correctamente y, efectivamente, resuelven el problema.

2022-10-04 10:04 UTC, danielsp13 commented
> Has realizado un esfuerzo considerable, y creo que estás muy cerca de alcanzar el objetivo. Los principales problemas son
> 
> 1. Concreta _el_ problema que quieres resolver.
> 2. Asegúrate de que tienes datos sobre el mismo, sea de tu amigo o sea de datos liberados sobre fútbol.
> 3. Aclara la lógica de negocio que vas a usar. No hace falta que la inventes, simplemente sigue algún algoritmo conocido. Asegúrate también que resuelve el problema
> 4. Asegúrate de que vas a poder programar, sin usar ninguna biblioteca externa, esa lógica de negocio.

Buenos días profesor. He leído todas las correcciones y estoy de acuerdo en todo lo que me ha dicho. Agradezco además que haya valorado el esfuerzo que he realizado. Reconozco que estoy tardando más de lo que tenía previsto en definir un problema acorde al objetivo, pero me encuentro motivado y ahora sí que me ha picado realmente la asignatura como para continuar enviando propuestas.

Entiendo que con las correcciones que me ha indicado, debería encontrar un problema que se pueda abordar mejor. Intentaré tenerla lista lo antes posible. Gracias por las indicaciones.

P.D: No soy mediapunta de un equipo de fúbtol, pero sí soy jugador de ajedrez. Así que no se preocupe, empezaré de cero las veces que haga falta hasta dar con la tecla. :smiley:

2022-10-04 11:20 UTC, JJ commented
> > Has realizado un esfuerzo considerable, y creo que estás muy cerca de alcanzar el objetivo. Los principales problemas son
> > 
> > 1. Concreta _el_ problema que quieres resolver.
> > 2. Asegúrate de que tienes datos sobre el mismo, sea de tu amigo o sea de datos liberados sobre fútbol.
> > 3. Aclara la lógica de negocio que vas a usar. No hace falta que la inventes, simplemente sigue algún algoritmo conocido. Asegúrate también que resuelve el problema
> > 4. Asegúrate de que vas a poder programar, sin usar ninguna biblioteca externa, esa lógica de negocio.
> 
> Buenos días profesor. He leído todas las correcciones y estoy de acuerdo en todo lo que me ha dicho. Agradezco además que haya valorado el esfuerzo que he realizado. Reconozco que estoy tardando más de lo que tenía previsto en definir un problema acorde al objetivo, pero me encuentro motivado y ahora sí que me ha picado realmente la asignatura como para continuar enviando propuestas.
> 

:+1:  Para eso estamos

> Entiendo que con las correcciones que me ha indicado, debería encontrar un problema que se pueda abordar mejor. Intentaré tenerla lista lo antes posible. Gracias por las indicaciones.

Yo creo que realmente el tema del fútbol puede dar mucho juego (:drum:). Este [TFG](https://github.com/ElenaMerelo/TFG), por ejemplo usa datos de StatBomb (o algo así) para analizar el juego en la Eurocopa femenina y en partidos específicos. Yo te animaría a seguir por ese camino, porque realmente puedes aprender cosas bastante interesantes, más que empezar desde cero.

> 
> P.D: No soy mediapunta de un equipo de fúbtol, pero sí soy jugador de ajedrez. Así que no se preocupe, empezaré de cero las veces que haga falta hasta dar con la tecla. smiley

Mira, uno de los que presentaron en años anteriores fue sobre asignación ¿suiza? de partidas en torneos open. En todo caso, yo creo que hablando con tu amigo sobre qué tipo de problemas aparecen y usando datos disponibles públicamente podría salir algo bastante interesante. Igual aplicando el problema de la mochila para la composición de un equipo, maximizando ??? y manteniendo constante ... ??? podría salir algo.

2022-10-04 18:47 UTC, danielsp13 commented
Buenas tardes profesor, he realizado una tarea de investigación bastante extensa he de decir y he llegado a las siguientes conclusiones que me gustaría compartir con usted para decidir un rumbo fijo.

> Yo creo que realmente el tema del fútbol puede dar mucho juego (drum). Este [TFG](https://github.com/ElenaMerelo/TFG), por ejemplo usa datos de StatBomb (o algo así) para analizar el juego en la Eurocopa femenina y en partidos específicos. Yo te animaría a seguir por ese camino, porque realmente puedes aprender cosas bastante interesantes, más que empezar desde cero.

Con respecto a la temática del fútbol, por desgracia creo que la voy a tener que abandonar. He leído el TFG que me envió (bastante interesante), y también he intentado abordar diversos aspectos sobre este deporte del que se puedan utilizar datos públicos. El problema que he encontrado es que la gran mayoría de datos interesantes o no son públicos o no me permiten gestionar una lógica de negocio suficiente.

> En todo caso, yo creo que hablando con tu amigo sobre qué tipo de problemas aparecen y usando datos disponibles públicamente podría salir algo bastante interesante. Igual aplicando el problema de la mochila para la composición de un equipo, maximizando ??? y manteniendo constante ... ??? podría salir algo.

Cuando le propuse mi idea, y me refería a _atributos_, tenía en mente algo similar a lo que sucede en el juego de EA Sports FIFA, en el que cada jugador tiene una serie de valores, y con ello se pueden hacer varias cosas, y quería complementar esto con una situación "más de la vida real", para aplicarlo a entrenamientos, formaciones...

Uno de los proyectos que podrían haber sido de interés es justo este asunto de generación de equipos de FIFA, tomando como base una cantidad de monedas fija para comprar a los jugadores, obteniendo el mejor equipo posible (en cuanto a calidad, química, etc). Sin embargo, esta información no es posible obtenerla (al menos de forma legal).
 
> Mira, uno de los que presentaron en años anteriores fue sobre asignación ¿suiza? de partidas en torneos open. 
Esta era una de las propuestas que descarté en principio porque no consideré que tuviese entidad suficiente como para justificar que debiera estar en la nube. Conozco este problema de muy buena mano desde el año pasado, cuando empecé a jugar torneos, y se me había ocurrido hacer una idea mejorada de este aspecto. El problema del emparejamiento del estilo suizo es que hay que tener en cuenta quién va ganando, perdiendo, cuántas se han jugado con blancas, cuantas con negras... etc. Sin embargo, como problema adicional al respecto no he visto un software que, a medida que se vayan terminando los emparejamientos (y el supuesto torneo), te prediga el ELO (puntuación de ajedrez) que has ganado o perdido y hubiera sido interesante. Entiendo que como ya lo hizo alguien , no puedo volver a abordar yo este problema.

Así que bueno, en toda esta tormenta de ideas que he ido teniendo, se me vino a la cabeza el siguiente problema que una profesora que tuve en la ESO de Historia me comentó, y es el problema de la corrección de exámenes de forma automatizada (evidentemente, no me refiero a exámenes tipo test). La idea consistiría aproximadamente en que el profesor tendría una batería de preguntas respondidas (a base de planilla), y los alumnos las contestarían, enviando su resolución, que sería comparada con la propuesta de solución del profesor a través de algoritmos de distancia / similitud de textos, y estos recibirían una calificación en función de cómo de cerca han estado de la propuesta del profesor. Como corregir un examen también tiene su factor subjetivo, quizá esta aplicación pueda servir para hacer "simulacros" o más bien para ayudar al profesor a ver las sensaciones generales de la clase sin mucho esfuerzo.

Con esto, si me da el visto bueno, me pongo a detallar todo adecuadamente a partir de mañana.

2022-10-04 18:56 UTC, JJ commented
El año pasado se propuso un problema similar, que consistía en generar exámenes con un nivel determinado, adaptándolo al nivel del estudiante. A priori, podría ser razonable, siempre que los algoritmos de distancia sean no triviales (incluyan distancias vectoriales sobre algún tipo de vector normalizado que represente el examen). Pero tendría que verlo desarrollado para aprobártelo, como es natural.

2022-10-05 08:34 UTC, danielsp13 commented
Buenos días, acabo de redactar la nueva propuesta que le comenté ayer. La respuesta a los items están en el cuerpo del PR. Espero que en esta ocasión podamos llegar a un acuerdo :)

2022-10-05 09:25 UTC, JJ approved these changes
Lo de que tengáis datos es bastante importante, porque si no no vais a hacer ningún tipo de test *serio* cuando sigáis avanzando, así que antes de fusionar esto o en PRs sucesivo añade algún tipo de repositorio de datos.

Por otro lado, también tendrás que tener en cuenta que los métodos de similitud no son totalmente precisos, y que la corrección no solamente se basa en la similitud de los textos, sino quizás en palabras clave o incluso frases clave. Eso son problemas que tendrás que plantear cuando llegues a la fase correspondiente.

2022-10-05 09:25 UTC, JJ commented on README.md
> +    Se requiere por parte del profesor, que introduzca una plantilla de preguntas y respuestas propuestas. Y por parte del alumno, se requiere que realice el examen propuesto.
Tendrás que buscar algún repositorio con preguntas y respuestas. En cuanto que tengas que introducir dos o tres, ya tienes un problema.

2022-10-05 10:35 UTC, merged

2022-10-16 07:45 UTC, JJ commented
No deberías retrasar más la entrega del objetivo 1. Ánimo.