[IV 22-23] : Objetivo 3
danielsp13/SuperCatch pull request #24
Opened 2022-12-16 21:34 UTC by danielsp13

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2022-12-18 19:16 UTC, danielsp13 commented
@JJ listo para revisión.

2022-12-19 08:50 UTC, JJ requested changes
El principal problema es no incluir la dependencia del gestor de tareas correctamente (ni de ninguna forma, de hecho)

2022-12-19 08:50 UTC, JJ commented on README.md
> +Para instalar las dependencias del proyecto:
¿No necesitas instalar nada antes? ¿Como el propio poe? (Última pregunta de la lista de comprobación)

2022-12-19 08:50 UTC, JJ commented on pyproject.toml
> +
Te faltaría la dependencia del gestor de tareas que uses. Si no la mencionas aquí. la documentación no es el lugar correcto para instalar dependencias (y ahí tampoco la has puesto)

2022-12-19 17:55 UTC, danielsp13 commented on README.md
> +Para instalar las dependencias del proyecto:
Sí. Desde luego ha sido fallo por mi parte obviar la instalación de poe cuando lo había considerado incluir en un principio. :pray:

2022-12-19 17:55 UTC, danielsp13 commented on pyproject.toml
> +
Realicé la instalación de poetry de forma global. Toda la razón, es un fallo importante.

2022-12-19 17:55 UTC, danielsp13 commented
Gracias por las correcciones @JJ , mañana corregiré lo mencionado.

2022-12-19 19:28 UTC, JJ commented
> Gracias por las correcciones @JJ , mañana corregiré lo mencionado.

No hay por qué darlas, es mi obligación. Se trata de que alcancéis los objetivos de aprendizaje.

2022-12-19 19:32 UTC, JJ commented on pyproject.toml
> +
El problema es que es una pescadilla que se muerde la cola. Si la instalas desde aquí, sólo podrás acceder si
1. Metes donde se instale en el path o 
2. Ejecutas poe con poetry run poe, porque sólo desde poetry tienes acceso al entorno virtual

No es fácil resolver eso por la interdependencia entre poetry y poe; pero o haces un target de poe para instalar poetry o instalas poe desde poetry (y haces alguna de las dos cosas de arriba). Pero no puedes dejar tanto poe como poetry como dependencias sin codificar en ningún fichero.

Tirando por la calle de enmedio, podrías usar requirements.txt para instalar estas dos cosas, siempre que se instalen globalmente al usuario. Cualquiera de las cosas que hagas es conveniente que abras un issue, cerrándolo con la opción que hayas elegido. Tienes que atender siempre al principio general: la configuración está en el entorno, no en la documentación.

2022-12-20 09:14 UTC, danielsp13 commented
@JJ, ¿qué tal así?

2022-12-20 09:48 UTC, JJ approved these changes
:ok_hand: en forma (implementación) y fondo (creación del issue #27)

2023-01-20 12:59 UTC, merged