[IV 22-23] : Objetivo 6
danielsp13/SuperCatch pull request #72
Opened 2023-02-06 22:08 UTC by danielsp13

* [ ] ¿Se ha evitado Circle CI, porque a estas alturas ya lo ha usado todo el
mundo?
* [ ] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [ ] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones del lenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean, tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están testeando y se ha comprobado que no se comprueban varias veces lo mismo (la misma versión en CI y en el contenedor Docker en otro sistema CI?

2023-02-07 00:07 UTC, danielsp13 commented
[https://github.com/danielsp13/SuperCatch/pull/72/commits/7c407db7c093e1dd9e5721a2eb06bde80e868df3](https://github.com/danielsp13/SuperCatch/pull/72/commits/7c407db7c093e1dd9e5721a2eb06bde80e868df3) y [https://github.com/danielsp13/SuperCatch/pull/72/commits/faff3996643b5daa05e8f90daf34e4e7f2f4337b](https://github.com/danielsp13/SuperCatch/pull/72/commits/faff3996643b5daa05e8f90daf34e4e7f2f4337b) realmente refieren a #75

2023-02-07 09:27 UTC, danielsp13 commented
Buenos días @JJ / revisor que vaya (o quiera) mirar este PR. Está listo para una revisión. Muchas gracias.

2023-02-07 20:05 UTC, manujurado1 approved these changes
¡Buenas de nuevo Daniel!

Me alegro que consiguieses alcanzar el objetivo 5 bastante rápido pese a esos problemillas que surgieron.
Le he echado un vistazo a tu PR y la verdad es que lo veo todo bien,  solo te he comentado una cosilla que entiendo que ha sido una confusión puntual. Mucha suerte!

2023-02-07 20:05 UTC, manujurado1 commented on docs/sistemas_ci.md
> +* **Python 3.11.1:** Esta versión es la que está en el *Contenedor Docker*, por lo que se hará esta comprobación en Cirrus. (Esta versión es la última lanzada que es estable).
Creo que esto lo has puesto al revés si no estoy yo equivocado. Ya que según he visto estás testeando desde docker usando *GitHub Actions*, por lo que presupongo que esta versión es la que tienes en docker ya que usas como imagen base la última versión estable.

2023-02-07 20:05 UTC, manujurado1 commented on tests/test_corrector.py
> -#=====================================================================
Y bueno sobre esto es lo mismo que en el otro objetivo, no debería aparecer ya que no tiene relación, pero al ser simples comentarios dudo que tenga importancia. 👍

2023-02-08 09:12 UTC, danielsp13 commented on docs/sistemas_ci.md
> +* **Python 3.11.1:** Esta versión es la que está en el *Contenedor Docker*, por lo que se hará esta comprobación en Cirrus. (Esta versión es la última lanzada que es estable).
:exclamation: totalmente cierto, al final lo acabé haciendo al revés y se me pasó hacer este cambio. gracias!!

2023-02-08 09:14 UTC, danielsp13 commented on tests/test_corrector.py
> -#=====================================================================
Esto lo único por lo que lo hice fue para pasar los tests a la hora de entregarlo, porque necesitaba que un último commit comprobase tareas (ya que las comprobaciones se lanzan únicamente cuando los cambios incluyen ficheros de código y no he hecho nada de esto en esta rama). Tuve en cuenta lo que me dijiste en el objetivo pero no tenía claro si cualquier commit servía así que por eso decidí hacerlo sobre esta rama por si la liaba.

2023-02-08 09:27 UTC, danielsp13 commented
@JJ, espero tu aprobación. :smile:

2023-02-08 09:47 UTC, JJ requested changes
Parece todo correcto, pero hay cosas en la configuración de cirrus que deberías revisar.

2023-02-08 09:47 UTC, JJ commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
???

2023-02-08 09:47 UTC, JJ commented on .cirrus.yml
> +   skip: "!changesInclude('**.py')"
Puede haber cambios en las dependencias que hay que testear también.

2023-02-08 11:21 UTC, danielsp13 commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
#76 , es necesario

2023-02-08 11:23 UTC, danielsp13 commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
a la hora de probarlo con github actions, no he tenido este problema porque al parecer la imagen que usa sí que o tiene un compilador, o lo resuelve de otra forma, mucho más lenta he de decir, me ha llegado a tardar 3 minutos, y realmente creo que sí me interesa probar esta versión que es la que está en desarrollo

2023-02-08 11:25 UTC, danielsp13 commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
y como está en desarrollo, relacionado con ese issue, estaban trabajando en una opción que permita la instalación como se ha venido haciendo en todas las versiones de python (pero está en discusión todavía)

2023-02-08 11:25 UTC, danielsp13 commented on .cirrus.yml
> +   skip: "!changesInclude('**.py')"
no se me había ocurrido la verdad, lo cambiaré.

2023-02-08 11:30 UTC, danielsp13 commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
el problema viene de la instalación de poetry (se haga vía pip o curl), a partir de una dependencia llamada `cffi`, que es la que lanza estos problemas. lo único que se me ocurre es explorar si puedo instalar esta dependencia directamente.

2023-02-08 11:31 UTC, danielsp13 commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
o no tener en cuenta esta versión y usar una por debajo de la 3.11, pero entre elegir una versión aleatoria sin ningún interés y la que está desarrollo, creo que está claro.

2023-02-08 11:36 UTC, danielsp13 commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
> el problema viene de la instalación de poetry (se haga vía pip o curl), a partir de una dependencia llamada cffi, que es la que lanza estos problemas. lo único que se me ocurre es explorar si puedo instalar esta dependencia directamente.

De hecho voy a investigar esto que realmente creo que es lo mejor..., lo abordaré en un issue relacionado con el que le he indicado.

2023-02-08 11:45 UTC, JJ commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
> el problema viene de la instalación de poetry (se haga vía pip o curl), a partir de una dependencia llamada `cffi`, que es la que lanza estos problemas. lo único que se me ocurre es explorar si puedo instalar esta dependencia directamente.

OK, entonces es por `poetry`, no tanto por la versión. Tiene sentido, aunque es extraño que cirrus no se prepare para eso.

2023-02-08 11:46 UTC, JJ commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
A menos que `cffi` se construya desde el fuente, tampoco veo la necesidad de que instales eso. Una opción es siempre ver la biblioteca que falla y ver si está empaquetada para Ubuntu o Debian. Muchas veces te evitas problemas de esa forma. Incluso, en este caso, instalar la versión de poetry que está empaquetada, siempre que use el Python del sistema (que supongo que lo hará)

2023-02-08 11:47 UTC, danielsp13 commented on .cirrus.yml
> +     apt-get install gcc libffi-dev -y
> > el problema viene de la instalación de poetry (se haga vía pip o curl), a partir de una dependencia llamada `cffi`, que es la que lanza estos problemas. lo único que se me ocurre es explorar si puedo instalar esta dependencia directamente.
> 
> OK, entonces es por `poetry`, no tanto por la versión. Tiene sentido, aunque es extraño que cirrus no se prepare para eso.

A mi también y sobre todo cuando al principio tenía pensado hacer estas comprobaciones con GitHub Actions. Acabé haciéndolo, y no me produjo ahí ningún tipo de fallo, salvo que la instalación de poetry tarda muchísimo en comparación con la versión 3.7, pero al fin y al cabo termina haciéndolo.

2023-02-08 12:55 UTC, danielsp13 commented
@JJ, he corregido el cambio que me ha indicado. Con respecto a lo que hemos hablado referente a #76 (abordado en #77) he comprobado que la mejor forma de solucionarlo es como lo tengo actualmente, al menos hasta que los desarrolladores de `cffi` lancen un paquete que no requiera de compilación previa (no hay ahora mismo para esta versión de python) o se resuelva la discusión actual sobre incluir una opción en la forma de instalar los paquetes de python como en todas las versiones existentes.

He probado eso, y también utilizar otras imágenes base, donde se resuelve el problema en aquellas que disponen de gcc (las versiones más reducidas como slim, no dispone de esto).

2023-02-08 13:03 UTC, JJ commented
> @JJ, he corregido el cambio que me ha indicado. Con respecto a lo que hemos hablado referente a #76 (abordado en #78) he comprobado que la mejor forma de solucionarlo es como lo tengo actualmente, al menos hasta que los desarrolladores de `cffi` lancen un paquete que no requiera de compilación previa (no hay ahora mismo para esta versión de python) o se resuelva la discusión actual sobre incluir una opción en la forma de instalar los paquetes de python como en todas las versiones existentes hasta la 3.11.
> 
> He probado eso, y también utilizar otras imágenes base, donde se resuelve el problema en aquellas que disponen de gcc (las versiones más reducidas como slim, no dispone de esto).

En general, debes tratar de proporcionar una solución mínima y viable a los problemas. ¿Has mirado si, como te digo, está empaquetado cffi para Debian? ¿Has visto [esto](https://packages.debian.org/bullseye/python3-cffi)? ¿O [`poetry`](https://packages.debian.org/search?searchon=names&keywords=poetry) directamente?

2023-02-08 16:02 UTC, danielsp13 commented
@JJ, en [https://github.com/danielsp13/SuperCatch/pull/72/commits/30d9ad4654eb98dfa126cf9e1afaeb816582789b](https://github.com/danielsp13/SuperCatch/pull/72/commits/30d9ad4654eb98dfa126cf9e1afaeb816582789b) he resuelto la cuestión abordada en #78 con lo que me había enlazado en el último comentario, pero después de eso surgió #79, así que considero que lo mejor es dejarlo como lo tenía.

2023-02-08 16:30 UTC, JJ commented
Sólo se ejecutan los tests en Cirrus, no se ejecutan los tests en GitHub actions. En "checks passed" sólo muestra dos de ellos.

2023-02-08 16:37 UTC, JJ requested changes
Aparte de lo encontrado, sigo viendo un problema que tengas que instalar gcc cada vez. Eso hace que un test tarde casi un minuto, de los cuales sólo un segundo es para el test  en sí. Hay varias cuestiones
* Nadie te obliga a que uses Cirrus. Si uno de tus requisitos es usar la versión rc de Python, deberías usar el runner en el que se pueda instalar sin necesidad de instalaciones adicionales.
* Incluso aunque necesites hacerlo, estás ejecutando la matriz de versiones en Cirrus, ejecutando esa instalación en versiones (la 3.7) donde no necesitas
* Incluso aunque necesites testear esa versión, tampoco te obliga nadie a que la ejecutes de esta forma. Lo más razonable para estas versiones es, precisamente, usar contenedores de test, que tendrían todo lo necesario instalado en la imagen y no tardarían un minuto en ejecutarse

Recuerda que no es la elección de herramienta la que tiene que condicionar tu configuración. Es tu configuración la que tiene que condicionar la elección de herramienta, de forma que se elija la más adecuada para las diferentes pruebas que se quieren hacer.

2023-02-08 16:37 UTC, JJ commented on .github/workflows/ci_docker.yml
> +         - '**.py'
Estos paths tendrías que modificarlos de la misma forma que el otro.

2023-02-08 17:34 UTC, danielsp13 commented on .github/workflows/ci_docker.yml
> +         - '**.py'
Entendido esto.

2023-02-08 17:36 UTC, danielsp13 commented
> Sólo se ejecutan los tests en Cirrus, no se ejecutan los tests en GitHub actions. En "checks passed" sólo muestra dos de ellos.

Se ejecutan si los cambios incluye 
 código en el push, como es el caso de [https://github.com/danielsp13/SuperCatch/pull/72/commits/e4d9e85a8ad9590d3b7762a5d67caddda284543b](https://github.com/danielsp13/SuperCatch/pull/72/commits/e4d9e85a8ad9590d3b7762a5d67caddda284543b), ¿debo definir una comprobación diferente en GitHub actions?

2023-02-08 17:39 UTC, JJ commented
> > Sólo se ejecutan los tests en Cirrus, no se ejecutan los tests en GitHub actions. En "checks passed" sólo muestra dos de ellos.
> 
> Se ejecutan si los cambios incluye código en el push, como es el caso de [e4d9e85](https://github.com/danielsp13/SuperCatch/commit/e4d9e85a8ad9590d3b7762a5d67caddda284543b), ¿debo definir una comprobación diferente en GitHub actions?

En general no, pero en este caso tengo que ir viendo check por check si se han ejecutado los dos o no. Normalmente cuando se está probando algo se incluyen los ficheros que se estén probando, en este caso los ficheros propios de los sistemas de CI. Luego se puede quitar después de fusionarlo.

2023-02-08 17:41 UTC, danielsp13 commented
> > > Sólo se ejecutan los tests en Cirrus, no se ejecutan los tests en GitHub actions. En "checks passed" sólo muestra dos de ellos.
> > 
> > 
> > Se ejecutan si los cambios incluye código en el push, como es el caso de [e4d9e85](https://github.com/danielsp13/SuperCatch/commit/e4d9e85a8ad9590d3b7762a5d67caddda284543b), ¿debo definir una comprobación diferente en GitHub actions?
> 
> En general no, pero en este caso tengo que ir viendo check por check si se han ejecutado los dos o no. Normalmente cuando se está probando algo se incluyen los ficheros que se estén probando, en este caso los ficheros propios de los sistemas de CI. Luego se puede quitar después de fusionarlo.

Vale, los siguientes cambios inlcuirán eso también para que lo pueda ver. Le volveré a mencionar cuando tenga todo listo.

2023-02-09 06:28 UTC, JJ approved these changes
👍

2023-02-09 08:30 UTC, merged